GET http://localhost:1234/hospital/

###

POST http://localhost:1234/hospital/admit
Content-Type: application/json

{
    "patientId":126,
    "patientName":"Dharun",
    "patientAge":20,
    "patientBloodGroup":"O+ve",
    "patientAddress":"Salem",
    "patientContact":9998889998,
    "issue":"Head-Ache",
    "status":"Discharge"
}

###


DELETE http://localhost:1234/hospital/discharge/Likkash

###


GET http://localhost:1234/hospital/issue/Fever

###


PUT http://localhost:1234/hospital/updateFever

###


PUT http://localhost:1234/hospital/updateCovid

###


DELETE http://localhost:1234/hospital/RemoveAge/19

###


DELETE http://localhost:1234/hospital/RemoveStatus/Terminated

###
