GET http://localhost:1234/hospital/

###

POST http://localhost:1234/hospital/admit
Content-Type: application/json

{
    "patientId":125,
    "patientName":"Vaishnavi",
    "patientAge":21,
    "patientBloodGroup":"B+v",
    "patientAddress":"Mallur",
    "patientContact":8838588068,
    "issue":"Head-Ache",
    "status":"Discharge"
}

###


DELETE http://localhost:1234/hospital/discharge/Likkash

###


GET http://localhost:1234/hospital/issue/Fever

###


PUT http://localhost:1234/hospital/updateFever

###


PUT http://localhost:1234/hospital/updateCovid

###


DELETE http://localhost:1234/hospital/RemoveAge/19

###


DELETE http://localhost:1234/hospital/RemoveStatus/Terminated

###


DELETE http://localhost:1234/hospital/erase/6694e67e57744e94bc4d6fd3

###

PUT http://localhost:1234/hospital
Content-Type: application/json

{
    "_id": "669898bf6c8322d155d407fe",
    "patientId":125,
    "patientName":"Vaishnavi",
    "patientAge":50,
    "patientBloodGroup":"B+v",
    "patientAddress":"Mallur",
    "patientContact":8838588068,
    "issue":"Head-Ache",
    "status":"Discharge"
}


###

GET http://localhost:1234/hospital/669503de6e660ed391bc01d1


###