GET http://localhost:1234/hospital/

###

POST http://localhost:1234/hospital/admit
Content-Type: application/json

{
    "patientId": 123,
    "patientName": "Likkash",
    "patientAge": 19,
    "patientBloodGroup": "B+v",
    "patientAddress": "Mallur",
    "patientContact": 6374746756,
    "issue": "Fever",
    "status": "Treatment"
}

###


DELETE http://localhost:1234/hospital/discharge/Likkash

###


GET http://localhost:1234/hospital/issue/Fever

###


PUT http://localhost:1234/hospital/updateFever

###


PUT http://localhost:1234/hospital/updateCovid

###


DELETE http://localhost:1234/hospital/RemoveAge/19

###


DELETE http://localhost:1234/hospital/RemoveStatus/Terminated

###


DELETE http://localhost:1234/hospital/erase/6694e67e57744e94bc4d6fd3

###